-- CUSTOMER DIMENSION
CREATE TABLE DRINKMIX_CUSTOMER(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    STREET VARCHAR2(50),
    HAUS_NUMBER VARCHAR2(20),
    ZIP_CODE NUMBER,
    CITY VARCHAR2(50),
    DATE_OF_BIRTH DATE,
    AGE_GROUP VARCHAR2(20),
    GENDER VARCHAR2(20)
);

-- PRODUCT DIMENSION
CREATE TABLE DRINKMIX_PRODUCT(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50),
    PRODUCT_CATEGORY VARCHAR2(50),
    PRODUCT_SIZE NUMBER,
    PRODUCT_PRICE NUMBER
);

-- BRANCH DIMENSION
CREATE TABLE DRINKMIX_BRANCH(
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR2(20),
    REGION VARCHAR2(20)
);

-- TIME DIMENSION
CREATE TABLE DRINKMIX_TIME(
    TIME_ID NUMBER PRIMARY KEY,
    DAY NUMBER NOT NULL,
    WEEK NUMBER NOT NULL,
    MONTH NUMBER NOT NULL,
    QUATER NUMBER NOT NULL,
    YEAR NUMBER NOT NULL
);

-- CUSTOMER MAP
CREATE TABLE CUSTOMER_BRANCH_MAP(
    CUSTOMER_ID NUMBER,
    BRANCH_ID NUMBER,
    SOURCE_CUSTOMER_ID NUMBER
);

-- PRODUCT MAP
CREATE TABLE PRODUCT_BRANCH_MAP(
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    SOURCE_PRODUCT_ID NUMBER
);
