CREATE TABLE DRINKMIX_FACT_SALES(
    TIME_ID NUMBER NOT NULL,
    CUSTOMER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    BRANCH_ID NUMBER NOT NULL,
    QUANTITY_LITER NUMBER,

    CONSTRAINT PK_FACT_SALES
    PRIMARY KEY(
        TIME_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        BRANCH_ID
    ),

    CONSTRAINT FK_TIME
        FOREIGN KEY (TIME_ID)
        REFERENCES DRINKMIX_TIME(TIME_ID),

    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DRINKMIX_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DRINKMIX_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DRINKMIX_BRANCH(BRANCH_ID)
);
