-- VW_ALL_CUSTOMERS to merge customers from different branches 
CREATE OR REPLACE VIEW VW_ALL_CUSTOMERS AS
(
SELECT
    1 AS BRANCH_ID,
    ID AS SOURCE_CUSTOMER_ID,
    SURNAME AS FIRST_NAME,
    NAME AS LAST_NAME,
    STR AS STREET,
    NO AS HAUS_NUMBER,
    ZIP AS ZIP_CODE,
    PLACE AS CITY,
    BDAY AS DATE_OF_BIRTH,
    CASE
        WHEN LOWER(GEND) = 'm' THEN 'Male'
        WHEN LOWER(GEND) = 'w' THEN 'Female'
    END AS GENDER
FROM DWT_BRANCH_1.CUSTOMER
UNION ALL
SELECT
    2 AS BRANCH_ID,
    c.NUM AS SOURCE_CUSTOMER_ID,
    c.FIRSTNAME AS FIRST_NAME,
    c.LASTNAME AS LAST_NAME,
    TRIM(
        REGEXP_REPLACE(
        STR_NO,
        '[0-9]+[A-Za-z]*$',
        ''
        )
    ) AS STREET,
    REGEXP_SUBSTR(STR_NO, '[0-9]+[A-Za-z]*$') AS HAUS_NUMBER,
    REGEXP_SUBSTR(ZIP_PLACE,'^[0-9]+') AS ZIP_CODE,
    TRIM(REGEXP_REPLACE(ZIP_PLACE,'^[0-9]+\s*','')) AS CITY,
    c.BDAY AS DATE_OF_BIRTH,
    'Unknown' AS GENDER
FROM DWT_BRANCH_2.CUSTOMER c
JOIN DWT_BRANCH_2.PLACE p
ON c.PLACEID = p.PLID
UNION ALL
SELECT
    3 AS BRANCH_ID,
    ID AS SOURCE_CUSTOMER_ID,
    SURNAME AS FIRST_NAME,
    NAME AS LAST_NAME,
    STR AS STREET,
    NO AS HAUS_NUMBER,
    ZIP AS ZIP_CODE,
    PLACE AS CITY,
    BDAY AS DATE_OF_BIRTH,
    CASE
        WHEN GEND = 1 THEN 'Male'
        WHEN GEND = 0 THEN 'Female'
    END AS GENDER
FROM DWT_BRANCH_3.CUSTOMER
);

-- VW_UNIQUE_CUSTOMERS to identify duplicate customers
REATE OR REPLACE VIEW VW_UNIQUE_CUSTOMERS AS
SELECT
    FIRST_NAME,
    LAST_NAME,
    STREET,
    HAUS_NUMBER,
    ZIP_CODE,
    CITY,
    COALESCE(
        MAX(CASE WHEN BRANCH_ID=1 THEN DATE_OF_BIRTH END),
        MAX(CASE WHEN BRANCH_ID=2 THEN DATE_OF_BIRTH END),
        MAX(CASE WHEN BRANCH_ID=3 THEN DATE_OF_BIRTH END)
    ) AS DATE_OF_BIRTH,
    COALESCE(
        MAX(CASE WHEN BRANCH_ID=1 THEN GENDER END),
        MAX(CASE WHEN BRANCH_ID=3 THEN GENDER END),
        'Unknown'
    ) AS GENDER
FROM VW_ALL_CUSTOMERS
GROUP BY
    FIRST_NAME,
    LAST_NAME,
    STREET,
    HAUS_NUMBER,
    ZIP_CODE,
    CITY;

-- VW_ALL_PRODUCTS to merge profucts from different branches 
CREATE OR REPLACE VIEW VW_ALL_PRODUCTS AS (
SELECT
    1 AS BRANCH_ID,
    ID AS SOURCE_PRODUCT_ID,
    NAME AS PRODUCT_NAME,
    SORT AS PRODUCT_CATEGORY,
    SZ AS PRODUCT_SIZE,
    PRICE AS PRODUCT_PRICE
FROM DWT_BRANCH_1.PRODUCTS
UNION ALL
SELECT
    2 AS BRANCH_ID,
    NUM AS SOURCE_PRODUCT_ID,
    LABEL AS PRODUCT_NAME,
    TYPE AS PRODUCT_CATEGORY,
    LITER AS PRODUCT_SIZE,
    TO_NUMBER(
           REPLACE(REPLACE(PRICE, '.0.', '0.'), '.', ',')
       ) AS PRODUCT_PRICE
FROM DWT_BRANCH_2.PRODUCT
UNION ALL
SELECT
    3 AS BRANCH_ID,
    p.ID AS SOURCE_PRODUCT_ID,
    p.NAME AS PRODUCT_NAME,
    CASE
        WHEN s.NAME = 'Alkoholisch'
            THEN 'Alcoholic'
        WHEN s.NAME = 'Alkoholfrei'
            THEN 'Non-Alcoholic'
        ELSE s.NAME
    END AS PRODUCT_CATEGORY,
    b.VOL AS PRODUCT_SIZE,
    p.PRICE AS PRODUCT_PRICE
FROM DWT_BRANCH_3.PRODUCT p
JOIN DWT_BRANCH_3.SORT s
    ON p.SID = s.SID
JOIN DWT_BRANCH_3.BOTTLE b
    ON p.OID = b.OID
);

-- VW_UNIQUE_PRODUCTS to identify duplicate products
CREATE OR REPLACE VIEW VW_UNIQUE_PRODUCTS AS
SELECT
    PRODUCT_NAME,
    PRODUCT_CATEGORY,
    PRODUCT_SIZE,
    PRODUCT_PRICE
FROM VW_ALL_PRODUCTS
GROUP BY
    PRODUCT_NAME,
    PRODUCT_CATEGORY,
    PRODUCT_SIZE,
    PRODUCT_PRICE;

-- VW_ALL_DATES to merge dates from different branches
CREATE OR REPLACE VIEW VW_ALL_DATES AS
SELECT "DATE" AS SALE_DATE
FROM DWT_BRANCH_1."ORDER"
UNION
SELECT "DATE" AS SALE_DATE
FROM DWT_BRANCH_2."BUYS"
UNION
SELECT "DATE" AS SALE_DATE
FROM DWT_BRANCH_3."ORDER";

-- VW_UNIQUE_DATES to identify duplicate dates
CREATE OR REPLACE VIEW VW_UNIQUE_DATES AS
SELECT DISTINCT
       TO_DATE(SALE_DATE,'dd.mm.yyyy') AS SALE_DATE
FROM VW_ALL_DATES;
