-- load the unique data into DRINKMIX_PRODUCT
CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO DRINKMIX_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_CATEGORY,
    PRODUCT_SIZE,
    PRODUCT_PRICE
)
SELECT
    PRODUCT_SEQ.NEXTVAL,
    PRODUCT_NAME,
    PRODUCT_CATEGORY,
    PRODUCT_SIZE,
    PRODUCT_PRICE
FROM VW_UNIQUE_PRODUCTS;
