--load the unique data into DRINKMIX_CUSTOMER
CREATE SEQUENCE CUSTOMER_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO DRINKMIX_CUSTOMER
(
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    STREET,
    HAUS_NUMBER,
    ZIP_CODE,
    CITY,
    DATE_OF_BIRTH,
    AGE_GROUP,
    GENDER
)
SELECT
    CUSTOMER_SEQ.NEXTVAL,
    FIRST_NAME,
    LAST_NAME,
    STREET,
    HAUS_NUMBER,
    ZIP_CODE,
    CITY,
    DATE_OF_BIRTH,
    CASE
        WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH)/12) <= 15
            THEN 'Child'
        WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH)/12) <= 19
            THEN 'Youngster'
        WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH)/12) <= 29
            THEN 'Young Adult'
        WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH)/12) <= 49
            THEN 'Adult'
        ELSE 'Old Adult'
    END,
    GENDER
FROM VW_UNIQUE_CUSTOMERS;

--Preserving Branch mapping of customers
CREATE TABLE CUSTOMER_BRANCH_MAP
(
    CUSTOMER_ID NUMBER,
    BRANCH_ID NUMBER,
    SOURCE_CUSTOMER_ID NUMBER,
    CONSTRAINT PK_CUSTOMER_BRANCH
    PRIMARY KEY
    (
        CUSTOMER_ID,
        BRANCH_ID,
        SOURCE_CUSTOMER_ID
    )
);
